const allProducts = [
  { 
    id: 101, 
    value: "Accessories",
    type: "Mouse",
    name: "XPG INFAREX M10",
    review: "68",
    price: "18",
    price2: "20",
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: "fa-solid fa-star",
    img: "img/offer/offer_1.png",
    img1: "",
    img2: "",
    img3: "",
    img4: "",
    img5: "",
  },
  { 
    id: 102,
    value: "Accessories",
    type: "Headphones",
    name: "Logitech G PRO X",
    review: "50",
    price: "180 ",
    price2: "200",
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: "fa-regular fa-star",
    img: "img/offer/offer_2.png",
    img1: "",
    img2: "",
    img3: "",
    img4: "",
    img5: "",
  },
  {
    id: 103,
    value: "Hardware",
    type: "Memory",
    name: "XPG D60G RGB 16GB",
    review: "36",
    price: "60",
    price2: "75",
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: "fa-solid fa-star",
    img: "img/offer/offer_3.png",
    img1: "",
    img2: "",
    img3: "",
    img4: "",
    img5: "",
  },
  { 
    id: 104,
    value: "Hardware",
    type: "Mother Board",
    name: "Asus Rog Strix Z790",
    review: "12",
    price: "350",
    price2: "390",
    star1: "fa-solid fa-star",
    star2: "fa-regular fa-star",
    star3: "fa-regular fa-star",
    img: "img/offer/offer_4.png",
    img1: "",
    img2: "",
    img3: "",
    img4: "",
    img5: "",
  },
  { 
    id: 105,
    value: "Hardware",
    type: "Procesor",
    name: "Intel i9-12900KS",
    review: "3",
    price: "799",
    price2: "930",
    star1: "fa-solid fa-star",
    star2: "fa-regular fa-star",
    star3: "fa-regular fa-star",
    img: "img/offer/offer_5.png",
    img1: "",
    img2: "",
    img3: "",
    img4: "",
    img5: "",
  },
  { 
    id: 106,
    value: "Other",
    type: "Monitor",
    name: "Msi G244F24 170HZ",
    review: "23",
    price: "205",
    price2: "240",
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: "fa-regular fa-star",
    img: "img/offer/offer_6.png",    
    img2: "",
    img3: "",
    img4: "",
    img5: "",
  },
  { 
    id: 107,
    value: "Accessories",
    type: "Watches",
    name: "Xiaomi Mi Band 5",
    review: "40",
    price: "199",
    price2: "250",
    star1: "fa-solid fa-star",
    star2: "fa-regular fa-star",
    star3: "fa-regular fa-star",
    img: "img/Products/product-1.png",
    img1: "",
    img2: "",
    img3: "",
    img4: "",
    img5: "",
  },
  { 
    id: 108,
    value: "Accessories",
    type: "Speaker",
    name: "Big Power Speaker",
    review: "50",
    price: "275 ",
    price2: "320",
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star-half-stroke",
    star3: "fa-regular fa-star",
    img: "img/Products/product-2.png",
    img1: "",
    img2: "",
    img3: "",
    img4: "",
    img5: "",
  },
  { 
    id: 109,
    value: "Other",
    type: "Camera",
    name: "WiFi Security Camera",
    review: "36",
    price: "399",
    price2: "460",
    star1: "fa-solid fa-star",
    star2: "fa-regular fa-star",
    star3: "fa-regular fa-star",
    img: "img/Products/product-3.png",
    img1: "",
    img2: "",
    img3: "",
    img4: "",
    img5: "",
  },
  { 
    id: 110,
    value: "Other",
    type: "Phones",
    name: "iphone 6x plus",
    review: "67",
    price: "400",
    price2: "460",
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: "fa-regular fa-star",
    img: "img/Products/product-4.png",
    img1: "",
    img2: "",
    img3: "",
    img4: "",
    img5: "",
  },
  {
    id: 111,
    value: "Accessories",
    type: "Speaker",
    name: "Mini Speaker",
    review: "22",
    price: "70",
    price2: "100",
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star-half-stroke",
    star3: "fa-regular fa-star",
    img: "img/Products/product-6.png",
    img1: "",
    img2: "",
    img3: "",
    img4: "",
    img5: "",
  },
  { 
    id: 112,
    value: "Accessories",
    type: "Headphones",
    name: "Wireless Headphones",
    review: "27",
    price: "350",
    price2: "390",
    star1: "fa-solid fa-star",
    star2: "fa-regular fa-star",
    star3: "fa-regular fa-star",
    img: "img/Products/product-5.png",
    img1: "",
    img2: "",
    img3: "",
    img4: "",
    img5: "",
  },
  { 
    id: 113,
    value: "Other",
    type: "Laptop",
    name: "Apple MacBook Air",
    review: "14",
    price: "899",
    price2: "1100",
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: " fa-regular fa-star",
    img: "img/Products/product-8.png",
    img1: "",
    img2: "",
    img3: "",
    img4: "",
    img5: "",
  },
  { 
    id: 114, 
    value: "Other",
    type: "Drone",
    name: "GoPro Karma Crone",
    review: "08",
    price: "850",
    price2: "1000",
    star1: "fa-solid fa-star",
    star2: "fa-solid fa-star",
    star3: "fa-solid fa-star",
    img: "img/single shop/drone-0.png",
    img1: "",
    img2: "",
    img3: "",
    img4: "",
    img5: "",
  }
];